license = "${license_url}"
issueTrackerURL = "${issues_url}"
sourcesUrl = "${sources_url}" # custom property that we parse ourselves

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL = "${homepage_url}"
logoFile = "logo.png"
credits = "${credits}"
authors = "Up, KiriCattus"
description = '''${description}'''

[dependencies]
"${mod_id}" = [
  { modId = "neoforge", type = "required", versionRange = "[${neoforge_version},)", ordering = "NONE", side = "BOTH", mc-publish = { ignore = true } },
  { modId = "minecraft", type = "required", versionRange = "[${minecraft_version}]", ordering = "NONE", side = "BOTH", mc-publish = { ignore = true } },
  { modId = "smartbrainlib", type = "required", versionRange = "[${smart_brain_lib_neoforge_version},)", ordering = "NONE", side = "BOTH", mc-publish = { curseforge = "661293", modrinth = "PuyPazRT" } },
  { modId = "geckolib", type = "required", versionRange = "[${geckolib_neoforge_version},)", ordering = "NONE", side = "BOTH", mc-publish = { curseforge = "388172", modrinth = "8BmcQJ2H" } },
  { modId = "resourcefulconfig", type = "required", versionRange = "[${resourceful_config_neoforge_version},)", ordering = "NONE", side = "BOTH", mc-publish = { curseforge = "", modrinth = "" } },
  { modId = "terrablender", type = "required", versionRange = "[${terrablender_neoforge_version},)", ordering = "NONE", side = "BOTH", mc-publish = { curseforge = "", modrinth = "" } },
]

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
[features.${mod_id}]
javaVersion="[${java_version},)"
#openGLVersion="[3.2,)"

[mc-publish]
curseforge = "${curseforge_id}"
modrinth = "${modrinth_id}"
loaders = ["neoforge"]
